Repository Growith-1-1/Backend, pull requests merged in 2025-04, with the labels that each got.

#12 7 feature 유저 crud 기능 추가, 10 유저 테스트 코드 작성
  src/main/java/dev/book/global/config/security/SecurityConfig.java
  src/main/java/dev/book/global/config/security/controller/AuthController.java
  src/main/java/dev/book/global/config/security/dto/CustomUserDetails.java
  src/main/java/dev/book/global/config/security/dto/oauth2/CustomOAuth2User.java
  src/main/java/dev/book/global/config/security/dto/oauth2/OAuth2Attributes.java
  src/main/java/dev/book/global/config/security/entity/RefreshToken.java
  src/main/java/dev/book/global/config/security/handler/OAuth2SuccessHandler.java
  src/main/java/dev/book/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/dev/book/global/config/security/jwt/JwtUtil.java
  src/main/java/dev/book/global/config/security/service/AuthService.java
  src/main/java/dev/book/global/config/security/service/CustomUserDetailsService.java
  src/main/java/dev/book/global/config/security/service/oauth2/CustomOAuth2UserService.java
  src/main/java/dev/book/global/config/security/service/oauth2/OAuth2AuthService.java
  src/main/java/dev/book/global/config/security/service/refresh/RefreshTokenService.java
  src/main/java/dev/book/global/config/security/util/CookieUtil.java
  src/main/java/dev/book/user/controller/UserController.java
  src/main/java/dev/book/user/dto/request/UserProfileUpdateRequest.java
  src/main/java/dev/book/user/dto/request/UserSignUpRequest.java
  src/main/java/dev/book/user/dto/response/UserProfileResponse.java
  src/main/java/dev/book/user/entity/UserEntity.java
  src/main/java/dev/book/user/exception/UserErrorCode.java
  src/main/java/dev/book/user/exception/UserErrorException.java
  src/main/java/dev/book/user/exception/UserNotFoundException.java
  src/main/java/dev/book/user/repository/UserRepository.java
  src/main/java/dev/book/user/service/UserService.java
  src/main/resources/application-test.yaml
  src/test/java/dev/book/global/config/security/controller/AuthControllerTest.java
  src/test/java/dev/book/user/controller/UserControllerTest.java
Labels: enhancement

#21 [fix] 허용된 url을 yml 파일로 관리, jwtFilter 스킵 #20
  src/main/java/dev/book/global/config/security/SecurityConfig.java
  src/main/java/dev/book/global/config/security/dto/PermitUrlProperties.java
  src/main/java/dev/book/global/config/security/filter/JwtAuthenticationFilter.java
  src/main/resources/application-jwt.yaml
Labels: bug

#25 14 feature 예산 기능 추가
  build.gradle
  src/main/java/dev/book/accountbook/controller/AccountBookController.java
  src/main/java/dev/book/accountbook/controller/BudgetController.java
  src/main/java/dev/book/accountbook/controller/StatController.java
  src/main/java/dev/book/accountbook/controller/swagger/AccountBookApi.java
  src/main/java/dev/book/accountbook/controller/swagger/BudgetApi.java
  src/main/java/dev/book/accountbook/controller/swagger/StatApi.java
  src/main/java/dev/book/accountbook/dto/event/SpendCreatedEvent.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookIncomeRequest.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookSpendRequest.java
  src/main/java/dev/book/accountbook/dto/request/BudgetRequest.java
  src/main/java/dev/book/accountbook/dto/request/Repeat.java
  src/main/java/dev/book/accountbook/dto/response/BudgetResponse.java
  src/main/java/dev/book/accountbook/entity/Budget.java
  src/main/java/dev/book/accountbook/entity/BudgetAccountBook.java
  src/main/java/dev/book/accountbook/exception/accountbook/AccountBookErrorCode.java
  src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
  src/main/java/dev/book/accountbook/repository/BudgetRepository.java
  src/main/java/dev/book/accountbook/repository/BudgetRepositoryCustom.java
  src/main/java/dev/book/accountbook/repository/BudgetRepositoryImpl.java
  src/main/java/dev/book/accountbook/service/AccountBookService.java
  src/main/java/dev/book/accountbook/service/BudgetService.java
  src/main/java/dev/book/accountbook/type/Frequency.java
  src/main/java/dev/book/accountbook/type/StringToCategoryConverter.java
  src/main/java/dev/book/accountbook/type/StringToFrequencyConverter.java
  src/main/java/dev/book/global/config/Firebase/FcmController.java
  src/main/java/dev/book/global/config/Firebase/FirebaseConfig.java
  src/main/java/dev/book/global/config/Firebase/entity/FcmToken.java
  src/main/java/dev/book/global/config/Firebase/exception/FcmTokenErrorCode.java
  src/main/java/dev/book/global/config/Firebase/exception/FcmTokenErrorException.java
  src/main/java/dev/book/global/config/Firebase/repository/FcmTokenRepository.java
  src/main/java/dev/book/global/config/Firebase/service/FCMService.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
Labels: enhancement

#28 27 bug 서버 쿠키 이슈
  src/main/java/dev/book/global/config/security/util/CookieUtil.java
  src/main/resources/application-swagger.yaml
Labels: bug

#31 9 feature 친구 rud 기능 추가, 테스트 코드 추가
  src/main/java/dev/book/global/config/security/SecurityConfig.java
  src/main/java/dev/book/user/entity/UserEntity.java
  src/main/java/dev/book/user/exception/UserErrorCode.java
  src/main/java/dev/book/user_friend/controller/UserFriendController.java
  src/main/java/dev/book/user_friend/controller/UserFriendSwaggerController.java
  src/main/java/dev/book/user_friend/dto/response/FriendDetailResponseDto.java
  src/main/java/dev/book/user_friend/dto/response/FriendListResponseDto.java
  src/main/java/dev/book/user_friend/dto/response/FriendRequestListResponseDto.java
  src/main/java/dev/book/user_friend/dto/response/KakaoResponseDto.java
  src/main/java/dev/book/user_friend/entity/UserFriend.java
  src/main/java/dev/book/user_friend/exception/UserFriendErrorCode.java
  src/main/java/dev/book/user_friend/exception/UserFriendException.java
  src/main/java/dev/book/user_friend/exception/UserFriendExceptionHandler.java
  src/main/java/dev/book/user_friend/repository/UserFriendRepository.java
  src/main/java/dev/book/user_friend/service/UserFriendService.java
  src/test/java/dev/book/user_friend/controller/UserFriendControllerTest.java
Labels: documentation, enhancement

#30 29 test 가계부 및 통계 테스트 코드 작성
  src/main/java/dev/book/accountbook/controller/AccountBookController.java
  src/main/java/dev/book/accountbook/controller/BudgetController.java
  src/main/java/dev/book/accountbook/controller/StatController.java
  src/main/java/dev/book/accountbook/controller/swagger/AccountBookApi.java
  src/main/java/dev/book/accountbook/controller/swagger/BudgetApi.java
  src/main/java/dev/book/accountbook/controller/swagger/StatApi.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookRequest.java
  src/main/java/dev/book/accountbook/entity/AccountBook.java
  src/main/java/dev/book/accountbook/entity/Budget.java
  src/main/java/dev/book/accountbook/entity/BudgetAccountBook.java
  src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
  src/main/java/dev/book/accountbook/service/AccountBookService.java
  src/main/java/dev/book/accountbook/service/BudgetService.java
  src/main/java/dev/book/accountbook/service/StatService.java
  src/test/java/dev/book/accountbook/service/AccountBookServiceIntegrationTest.java
  src/test/java/dev/book/accountbook/service/AccountBookServiceUnitTest.java
  src/test/java/dev/book/accountbook/service/StatServiceIntegrationTest.java
  src/test/java/dev/book/accountbook/service/StatServiceUnitTest.java
  src/test/java/dev/book/global/config/security/controller/AuthControllerTest.java
Labels: enhancement

#37 [fix] enum 대소문자 변환 로직 추가
  src/main/java/dev/book/accountbook/type/Category.java
  src/main/java/dev/book/accountbook/type/Frequency.java
Labels: bug

#42 41 refactor 카테고리 테이블 분리
  src/main/java/dev/book/accountbook/controller/AccountBookController.java
  src/main/java/dev/book/accountbook/controller/StatController.java
  src/main/java/dev/book/accountbook/controller/swagger/AccountBookApi.java
  src/main/java/dev/book/accountbook/controller/swagger/StatApi.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookIncomeRequest.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookRequest.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookSpendRequest.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookCategoryResponse.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookIncomeResponse.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookSpendResponse.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookStatResponse.java
  src/main/java/dev/book/accountbook/entity/AccountBook.java
  src/main/java/dev/book/accountbook/entity/Budget.java
  src/main/java/dev/book/accountbook/entity/middle/AccountBookCategory.java
  src/main/java/dev/book/accountbook/entity/middle/BudgetAccountBook.java
  src/main/java/dev/book/accountbook/entity/middle/BudgetCategory.java
  src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
  src/main/java/dev/book/accountbook/service/AccountBookService.java
  src/main/java/dev/book/accountbook/service/BudgetService.java
  src/main/java/dev/book/accountbook/service/StatService.java
  src/main/java/dev/book/accountbook/type/StringToCategoryConverter.java
  src/main/java/dev/book/global/entity/Category.java
  src/main/java/dev/book/global/repository/CategoryRepository.java
  src/main/java/dev/book/user/dto/request/UserSignUpRequest.java
  src/main/java/dev/book/user/entity/UserEntity.java
Labels: enhancement

#44 40 refactor 로직 리팩토링 및 user 단위 테스트 추가
  build.gradle
  src/main/java/dev/book/accountbook/type/Category.java
  src/main/java/dev/book/global/config/security/handler/OAuth2SuccessHandler.java
  src/main/java/dev/book/user/entity/UserEntity.java
  src/main/java/dev/book/user/user_friend/controller/UserFriendController.java
  src/main/java/dev/book/user/user_friend/controller/UserFriendSwaggerController.java
  src/main/java/dev/book/user/user_friend/dto/EncryptUserInfo.java
  src/main/java/dev/book/user/user_friend/dto/response/FriendDetailResponseDto.java
  src/main/java/dev/book/user/user_friend/dto/response/FriendListResponseDto.java
  src/main/java/dev/book/user/user_friend/dto/response/FriendRequestListResponseDto.java
  src/main/java/dev/book/user/user_friend/dto/response/InvitingUserTokenResponseDto.java
  src/main/java/dev/book/user/user_friend/dto/response/KakaoResponseDto.java
  src/main/java/dev/book/user/user_friend/entity/UserFriend.java
  src/main/java/dev/book/user/user_friend/exception/UserFriendErrorCode.java
  src/main/java/dev/book/user/user_friend/exception/UserFriendException.java
  src/main/java/dev/book/user/user_friend/exception/UserFriendExceptionHandler.java
  src/main/java/dev/book/user/user_friend/repository/UserFriendRepository.java
  src/main/java/dev/book/user/user_friend/service/UserFriendService.java
  src/main/java/dev/book/user/user_friend/util/AESUtil.java
  src/main/java/dev/book/user_friend/dto/response/FriendDetailResponseDto.java
  src/test/java/dev/book/accountbook/service/AccountBookServiceIntegrationTest.java
  src/test/java/dev/book/accountbook/service/StatServiceIntegrationTest.java
  src/test/java/dev/book/challenge/service/ChallengeInviteServiceTest.java
  src/test/java/dev/book/challenge/service/ChallengeServiceTest.java
  src/test/java/dev/book/global/config/security/controller/AuthControllerTest.java
  src/test/java/dev/book/global/config/security/service/AuthServiceUnitTest.java
  src/test/java/dev/book/user/controller/UserControllerTest.java
  src/test/java/dev/book/user/service/UserServiceUnitTest.java
  src/test/java/dev/book/user/user_friend/controller/UserFriendControllerTest.java
  src/test/java/dev/book/util/CookieTestUtil.java
  src/test/java/dev/book/util/UserBuilder.java
Labels: documentation

#45 43 feature codef api 추가
  src/main/java/dev/book/accountbook/controller/AccountBookController.java
  src/main/java/dev/book/accountbook/controller/BudgetController.java
  src/main/java/dev/book/accountbook/controller/CodefController.java
  src/main/java/dev/book/accountbook/controller/StatController.java
  src/main/java/dev/book/accountbook/controller/swagger/AccountBookApi.java
  src/main/java/dev/book/accountbook/controller/swagger/CodefApi.java
  src/main/java/dev/book/accountbook/controller/swagger/StatApi.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookIncomeRequest.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookRequest.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookSpendListRequest.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookSpendRequest.java
  src/main/java/dev/book/accountbook/dto/request/BudgetRequest.java
  src/main/java/dev/book/accountbook/dto/request/CreateConnectedIdRequest.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookIncomeResponse.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookSpendResponse.java
  src/main/java/dev/book/accountbook/entity/AccountBook.java
  src/main/java/dev/book/accountbook/entity/Budget.java
  src/main/java/dev/book/accountbook/entity/Codef.java
  src/main/java/dev/book/accountbook/entity/middle/AccountBookCategory.java
  src/main/java/dev/book/accountbook/entity/middle/BudgetCategory.java
  src/main/java/dev/book/accountbook/exception/codef/CodefErrorCode.java
  src/main/java/dev/book/accountbook/exception/codef/CodefErrorException.java
  src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
  src/main/java/dev/book/accountbook/repository/CodefRepository.java
  src/main/java/dev/book/accountbook/service/AccountBookService.java
  src/main/java/dev/book/accountbook/service/CodefService.java
  src/main/java/dev/book/accountbook/service/StatService.java
  src/main/java/dev/book/accountbook/type/Bank.java
  src/main/java/dev/book/accountbook/type/Category.java
  src/main/java/dev/book/global/config/bean/RestTemplateConfig.java
  src/main/java/dev/book/global/entity/Category.java
  src/main/java/dev/book/global/repository/CategoryRepository.java
  src/main/java/dev/book/global/util/RsaEncryptUtil.java
  src/main/resources/application-codef.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
Labels: enhancement

#46 35 feature 업적 기능 구현
  src/main/java/dev/book/accountbook/repository/BudgetRepository.java
  src/main/java/dev/book/accountbook/scheduler/AccountBookScheduler.java
  src/main/java/dev/book/accountbook/service/AccountBookService.java
  src/main/java/dev/book/accountbook/service/BudgetService.java
  src/main/java/dev/book/accountbook/service/StatService.java
  src/main/java/dev/book/achievement/achievement_user/IndividualAchievementStatusService.java
  src/main/java/dev/book/achievement/achievement_user/entity/AchievementUser.java
  src/main/java/dev/book/achievement/achievement_user/entity/IndividualAchievementStatus.java
  src/main/java/dev/book/achievement/achievement_user/repository/AchievementUserRepository.java
  src/main/java/dev/book/achievement/achievement_user/repository/IndividualAchievementStatusRepository.java
  src/main/java/dev/book/achievement/dto/AchievementResponseDto.java
  src/main/java/dev/book/achievement/dto/event/GetAchievementEvent.java
  src/main/java/dev/book/achievement/entity/Achievement.java
  src/main/java/dev/book/achievement/exception/AchievementErrorCode.java
  src/main/java/dev/book/achievement/exception/AchievementException.java
  src/main/java/dev/book/achievement/exception/AchievementExceptionHandler.java
  src/main/java/dev/book/achievement/repository/AchievementRepository.java
  src/main/java/dev/book/achievement/service/AchievementService.java
  src/main/java/dev/book/challenge/entity/Challenge.java
  src/main/java/dev/book/challenge/repository/ChallengeRepository.java
  src/main/java/dev/book/challenge/scheduler/ChallengeScheduler.java
  src/main/java/dev/book/challenge/service/ChallengeInviteService.java
  src/main/java/dev/book/challenge/service/ChallengeService.java
  src/main/java/dev/book/global/config/Firebase/service/FCMService.java
  src/main/java/dev/book/global/config/security/filter/JwtAuthenticationFilter.java
  src/main/java/dev/book/global/config/security/repository/RefreshTokenRepository.java
  src/main/java/dev/book/global/config/security/service/AuthService.java
  src/main/java/dev/book/global/config/security/service/refresh/RefreshTokenService.java
  src/main/java/dev/book/global/exception/category/CategoryErrorCode.java
  src/main/java/dev/book/global/exception/category/CategoryException.java
  src/main/java/dev/book/user/controller/UserController.java
  src/main/java/dev/book/user/controller/UserSwaggerController.java
  src/main/java/dev/book/user/dto/request/UserCategoriesRequest.java
  src/main/java/dev/book/user/dto/request/UserSignUpRequest.java
  src/main/java/dev/book/user/entity/UserEntity.java
  src/main/java/dev/book/user/scheduler/UserScheduler.java
  src/main/java/dev/book/user/service/UserService.java
  src/main/java/dev/book/user/user_category/UserCategory.java
  src/main/java/dev/book/user/user_friend/service/UserFriendService.java
Labels: enhancement

#50 49 refactor 지출 수입 수동 등록 시 시간을 직접 입력할 수 있게 변경
  src/main/java/dev/book/accountbook/controller/swagger/AccountBookApi.java
  src/main/java/dev/book/accountbook/controller/swagger/StatApi.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookIncomeRequest.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookRequest.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookSpendRequest.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookIncomeResponse.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookSpendResponse.java
  src/main/java/dev/book/accountbook/entity/AccountBook.java
  src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
  src/main/java/dev/book/accountbook/repository/BudgetRepositoryImpl.java
  src/main/java/dev/book/accountbook/service/AccountBookService.java
  src/main/java/dev/book/accountbook/service/BudgetService.java
  src/main/java/dev/book/accountbook/service/CodefService.java
  src/main/java/dev/book/accountbook/service/StatService.java
  src/main/java/dev/book/accountbook/type/Frequency.java
Labels: enhancement

#56 55 feature 캘린더를 위한 api 추가
  src/main/java/dev/book/accountbook/controller/AccountBookController.java
  src/main/java/dev/book/accountbook/controller/BudgetController.java
  src/main/java/dev/book/accountbook/controller/CodefController.java
  src/main/java/dev/book/accountbook/controller/swagger/AccountBookApi.java
  src/main/java/dev/book/accountbook/controller/swagger/BudgetApi.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookIncomeRequest.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookListRequest.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookMonthRequest.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookRequest.java
  src/main/java/dev/book/accountbook/dto/request/AccountBookSpendRequest.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookIncomeResponse.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookMonthResponse.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookPeriodResponse.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookSpendResponse.java
  src/main/java/dev/book/accountbook/dto/response/BudgetResponse.java
  src/main/java/dev/book/accountbook/entity/AccountBook.java
  src/main/java/dev/book/accountbook/exception/accountbook/AccountBookErrorCode.java
  src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
  src/main/java/dev/book/accountbook/repository/BudgetRepository.java
  src/main/java/dev/book/accountbook/repository/querydsl/BudgetRepositoryCustom.java
  src/main/java/dev/book/accountbook/repository/querydsl/BudgetRepositoryImpl.java
  src/main/java/dev/book/accountbook/service/AccountBookService.java
  src/main/java/dev/book/accountbook/service/BudgetService.java
  src/main/java/dev/book/accountbook/service/StatService.java
  src/test/java/dev/book/accountbook/controller/AccountBookControllerTest.java
  src/test/java/dev/book/accountbook/service/AccountBookServiceUnitTest.java
  src/test/java/dev/book/accountbook/service/StatServiceUnitTest.java
Labels: enhancement

#65 24, 40, 58 feature 유저 기능 중 프론트 측 요구 api 추가 및 유저 기능 추가
  src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
  src/main/java/dev/book/achievement/achievement_user/entity/AchievementUser.java
  src/main/java/dev/book/achievement/achievement_user/repository/AchievementUserRepository.java
  src/main/java/dev/book/achievement/entity/Achievement.java
  src/main/java/dev/book/challenge/challenge_invite/entity/ChallengeInvite.java
  src/main/java/dev/book/challenge/scheduler/ChallengeScheduler.java
  src/main/java/dev/book/challenge/service/ChallengeInviteService.java
  src/main/java/dev/book/challenge/service/ChallengeService.java
  src/main/java/dev/book/global/config/jpa/JpaConfig.java
  src/main/java/dev/book/global/config/security/SecurityConfig.java
  src/main/java/dev/book/global/config/security/util/CookieUtil.java
  src/main/java/dev/book/user/controller/UserController.java
  src/main/java/dev/book/user/controller/UserSwaggerController.java
  src/main/java/dev/book/user/dto/response/UserAchievementResponse.java
  src/main/java/dev/book/user/dto/response/UserCategoryResponse.java
  src/main/java/dev/book/user/dto/response/UserChallengeInfoResponse.java
  src/main/java/dev/book/user/entity/UserEntity.java
  src/main/java/dev/book/user/exception/UserErrorCode.java
  src/main/java/dev/book/user/repository/UserRepository.java
  src/main/java/dev/book/user/service/UserService.java
  src/main/java/dev/book/user/user_friend/controller/UserFriendSwaggerController.java
  src/main/java/dev/book/user/user_friend/exception/UserFriendErrorCode.java
  src/main/java/dev/book/user/user_friend/repository/UserFriendRepository.java
  src/main/java/dev/book/user/user_friend/service/UserFriendService.java
  src/main/resources/application-local.yaml
  src/test/java/dev/book/user/service/UserServiceUnitTest.java
  src/test/java/dev/book/user/user_friend/service/UserFriendServiceUnitTest.java
  src/test/java/dev/book/util/UserBuilder.java
Labels: documentation, enhancement

#68 61 feat 예산 대비 과소비 알림 추가
  src/main/java/dev/book/accountbook/entity/Budget.java
  src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
  src/main/java/dev/book/accountbook/repository/BudgetRepository.java
  src/main/java/dev/book/accountbook/repository/querydsl/BudgetRepositoryCustom.java
  src/main/java/dev/book/accountbook/repository/querydsl/BudgetRepositoryImpl.java
  src/main/java/dev/book/accountbook/service/AccountBookService.java
  src/main/java/dev/book/accountbook/service/StatService.java
  src/main/java/dev/book/accountbook/type/BudgetLimit.java
  src/main/java/dev/book/accountbook/type/Frequency.java
  src/main/java/dev/book/accountbook/type/PeriodRange.java
  src/main/java/dev/book/global/config/Firebase/FcmController.java
  src/main/java/dev/book/global/config/Firebase/service/FCMService.java
  src/test/java/dev/book/accountbook/service/AccountBookServiceIntegrationTest.java
  src/test/java/dev/book/accountbook/service/AccountBookServiceUnitTest.java
  src/test/java/dev/book/accountbook/service/StatServiceIntegrationTest.java
  src/test/java/dev/book/accountbook/service/StatServiceUnitTest.java
Labels: enhancement

#73 70 test budget 서비스 테스트 작성
  src/main/java/dev/book/accountbook/controller/BudgetController.java
  src/main/java/dev/book/accountbook/repository/BudgetRepository.java
  src/main/java/dev/book/accountbook/service/AccountBookService.java
  src/main/java/dev/book/accountbook/service/BudgetService.java
  src/test/java/dev/book/accountbook/service/AccountBookServiceIntegrationTest.java
  src/test/java/dev/book/accountbook/service/BudgetServiceIntegrationTest.java
  src/test/java/dev/book/accountbook/service/BudgetServiceUnitTest.java
  src/test/java/dev/book/accountbook/service/StatServiceIntegrationTest.java
Labels: enhancement

#71 67 feature sse 설정 추가
  src/main/java/dev/book/achievement/service/AchievementService.java
  src/main/java/dev/book/challenge/controller/ChallengeController.java
  src/main/java/dev/book/challenge/controller/ChallengeInviteController.java
  src/main/java/dev/book/challenge/controller/swagger/ChallengeApi.java
  src/main/java/dev/book/challenge/controller/swagger/ChallengeInviteApi.java
  src/main/java/dev/book/global/config/security/controller/AuthController.java
  src/main/java/dev/book/global/config/security/controller/swagger/AuthApi.java
  src/main/java/dev/book/global/sse/controller/SseController.java
  src/main/java/dev/book/global/sse/controller/swagger/SseApi.java
  src/main/java/dev/book/global/sse/dto/SseResponse.java
  src/main/java/dev/book/global/sse/repository/SseEmitterRepository.java
  src/main/java/dev/book/global/sse/repository/SseEmitterRepositoryImpl.java
  src/main/java/dev/book/global/sse/service/SseService.java
  src/main/java/dev/book/global/sse/type/SseType.java
  src/main/java/dev/book/user/controller/UserController.java
  src/main/java/dev/book/user/controller/swagger/UserApi.java
  src/main/java/dev/book/user/user_friend/controller/UserFriendController.java
  src/main/java/dev/book/user/user_friend/controller/swagger/UserFriendApi.java
  src/test/java/dev/book/global/sse/service/SseServiceTest.java
Labels: enhancement

#79 76 feature 매일 계좌 동기화
  src/main/java/dev/book/accountbook/controller/AccountBookController.java
  src/main/java/dev/book/accountbook/controller/CodefController.java
  src/main/java/dev/book/accountbook/controller/StatController.java
  src/main/java/dev/book/accountbook/controller/swagger/AccountBookApi.java
  src/main/java/dev/book/accountbook/controller/swagger/CodefApi.java
  src/main/java/dev/book/accountbook/dto/event/CreateTransEvent.java
  src/main/java/dev/book/accountbook/dto/response/TempAccountBookResponse.java
  src/main/java/dev/book/accountbook/entity/TempAccountBook.java
  src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
  src/main/java/dev/book/accountbook/repository/CodefRepository.java
  src/main/java/dev/book/accountbook/repository/TempAccountBookRepository.java
  src/main/java/dev/book/accountbook/scheduler/AccountBookScheduler.java
  src/main/java/dev/book/accountbook/service/AccountBookService.java
  src/main/java/dev/book/accountbook/service/CodefService.java
  src/main/java/dev/book/global/config/Firebase/service/FCMService.java
  src/test/java/dev/book/accountbook/service/BudgetServiceUnitTest.java
Labels: enhancement

#86 85 fix 요청 중복
  src/main/java/dev/book/accountbook/controller/StatController.java
  src/main/java/dev/book/accountbook/controller/swagger/BudgetApi.java
  src/main/java/dev/book/accountbook/controller/swagger/StatApi.java
  src/main/java/dev/book/accountbook/repository/TempAccountBookRepository.java
  src/main/java/dev/book/accountbook/service/AccountBookService.java
Labels: bug

#93 [fix] 쿠키 설정 수정 및 access_token 만료 시간 수정 #92
  src/main/java/dev/book/global/config/security/util/CookieUtil.java
  src/main/resources/application-jwt.yaml
Labels: bug

#96 [fix] 로그인 실패 시 redirectUrl 변경 및 docs 수정 #92
  src/main/java/dev/book/global/config/security/handler/OAuth2FailureHandler.java
  src/main/java/dev/book/user/user_friend/controller/swagger/UserFriendApi.java
Labels: bug, documentation

#87 83 84 refactor 기능적 요소 수정 및 리팩토링, 테스트 코드 작성
  src/main/java/dev/book/accountbook/scheduler/AccountBookScheduler.java
  src/main/java/dev/book/achievement/achievement_user/entity/IndividualAchievementStatus.java
  src/main/java/dev/book/achievement/achievement_user/repository/AchievementUserRepository.java
  src/main/java/dev/book/achievement/achievement_user/repository/IndividualAchievementStatusRepository.java
  src/main/java/dev/book/achievement/achievement_user/service/IndividualAchievementStatusService.java
  src/main/java/dev/book/achievement/service/AchievementService.java
  src/main/java/dev/book/global/sse/service/SseService.java
  src/main/java/dev/book/tip/controller/TipController.java
  src/main/java/dev/book/user/entity/UserEntity.java
  src/main/java/dev/book/user/service/UserService.java
  src/test/java/dev/book/accountbook/service/AccountBookServiceUnitTest.java
  src/test/java/dev/book/achievement/achievement_user/service/IndividualAchievementStatusServiceTest.java
  src/test/java/dev/book/achievement/service/AchievementServiceTest.java
  src/test/java/dev/book/challenge/controller/ChallengeControllerTest.java
  src/test/java/dev/book/tip/service/TipServiceTest.java
  src/test/java/dev/book/user/service/UserServiceUnitTest.java
Labels: bug, documentation, enhancement

#97 89 feature 페이징 추가
  src/main/java/dev/book/accountbook/controller/AccountBookController.java
  src/main/java/dev/book/accountbook/controller/BudgetController.java
  src/main/java/dev/book/accountbook/controller/StatController.java
  src/main/java/dev/book/accountbook/controller/swagger/AccountBookApi.java
  src/main/java/dev/book/accountbook/controller/swagger/BudgetApi.java
  src/main/java/dev/book/accountbook/controller/swagger/StatApi.java
  src/main/java/dev/book/accountbook/dto/request/BudgetFindRequest.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookIncomeListResponse.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookPeriodListResponse.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookPeriodResponse.java
  src/main/java/dev/book/accountbook/dto/response/AccountBookSpendListResponse.java
  src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
  src/main/java/dev/book/accountbook/repository/BudgetRepository.java
  src/main/java/dev/book/accountbook/service/AccountBookService.java
  src/main/java/dev/book/accountbook/service/BudgetService.java
  src/main/java/dev/book/accountbook/service/StatService.java
  src/test/java/dev/book/accountbook/service/AccountBookServiceIntegrationTest.java
  src/test/java/dev/book/accountbook/service/AccountBookServiceUnitTest.java
  src/test/java/dev/book/accountbook/service/BudgetServiceIntegrationTest.java
  src/test/java/dev/book/accountbook/service/BudgetServiceUnitTest.java
  src/test/java/dev/book/accountbook/service/StatServiceIntegrationTest.java
  src/test/java/dev/book/accountbook/service/StatServiceUnitTest.java
Labels: enhancement

#102 101 fix gradle 패키지 수정
  build.gradle
Labels: bug

#108 105 refactor 코드 최적화
  src/main/java/dev/book/accountbook/repository/TempAccountBookRepository.java
  src/main/java/dev/book/accountbook/service/AccountBookService.java
Labels: enhancement
